# -*- coding: utf-8 -*-
"""sibgrapi2018_gender detect.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-2jCDBldgP5u9fIruvd1ABsG5uWVXZzw

### Training a gender detector model on darknet with celebA and PascalVoc
"""

!unzip sibgrapi2018_gender_detection-master

"""### Running the gender detector on darknet"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/sibgrapi2018_gender_detection-master/code/darknet

!make

#학습된 가중치 설치
!wget http://inf.ufrgs.br/~lfazeni/sib2018_models/gender_detection_50voc_50celeb_darknet.weights

# run darknet detection on test images 
# 경로 - sibgrapi2018_gender_detection-master folder 밖
!./darknet detector demo cfg/test_voc_only.data cfg/yoloGender.cfg gender_detection_50voc_50celeb_darknet.weights ../../../face_0.jpg

!./darknet detector demo cfg/test_voc_only.data cfg/yoloGender.cfg gender_detection_50voc_50celeb_darknet.weights../../data/vid/001.mp4
#!./darknet detector demo cfg/test_voc_only.data cfg/yoloGender.cfg gender_detection_50voc_50celeb_darknet.weights ../../data/vid/001.mp4 -i 0 -out_filename results.avi
#!./darknet detector demo cfg/coco.data cfg/yolov4.cfg yolov4.weights -dont_show test.mp4 -i 0 -out_filename results.avi